Implemented Feature: EventCategory plain enum To enum class.
TheCherno/Hazel pull request #332
Opened 2020-09-10 10:16 UTC by babaliaris

#### Issue Description.
The plain enum **EventCategory** was causing a *warning* because plain enums are globally scoped!
enum class should be always used instead of plain enums. You can read more about it here:
https://stackoverflow.com/questions/18335861/why-is-enum-class-preferred-over-plain-enum

#### How did I fix it:
- [x] I changed the **EventCategory** plain enum to an **enum class**.
- [x] In order for the **bitwise operations** to work `EVENT_CLASS_CATEGORY(EventCategory::EventCategoryMouse | EventCategory::EventCategoryInput)` I had to overload the bitwise operators of the enum class **EventCategory**. So, I created a new **Event.cpp** file inside **Hazel/src/Events/** and implemented the overloading of the bitwise operators there.

- [x] Finally I had to change the virtual function **GetCategoryFlags()** to return an **EventCategory** instead of an int.
also I had to typecast the return value of **IsInCategory()** to a bool.

Here you can see how **overloading enum class bitwise operations** work:
https://blog.bitwigglers.org/using-enum-classes-as-type-safe-bitmasks/

Thank you for your time!

2020-09-14 09:57 UTC, 3x3y3z3t requested changes

2020-09-14 11:20 UTC, babaliaris commented on Hazel/src/Hazel/Events/ApplicationEvent.h
> +		EVENT_CLASS_CATEGORY(EventCategory::EventCategoryApplication)
Yeap, I thought of doing that :P If you want you can do it and send me a pull request to get the credits.

2020-09-23 14:24 UTC, babaliaris commented
I just resolved some **imgui.ini** file conflicts with Cherno's new commit to the master branch. Now the **imgui.ini** is completely clear from changes from this pull request!

2020-10-06 14:10 UTC, babaliaris commented
Don't really worry about that imgui.ini commits. I tried to make the changes disappear but for some reason, GitHub likes to add a new line at the end of the imgui.ini file while Cherno's current commit does not contain that new line.

2022-06-28 08:30 UTC, TheCherno commented
We should just keep using enums for this case 👍

2022-06-28 08:30 UTC, closed without merging

2022-08-23 20:18 UTC, sliptime commented
If the warning still feels like an annoying kid mocking you for not having gotten a complete 0 out of 0 Warnings, you can place: 
```
#pragma warning(disable : 26812)
```
at the top of Event.h, it will disable the enum class warning.