Added a custom event system
TheCherno/Hazel pull request #357
Opened 2020-10-26 14:16 UTC by Sausty

## Added support for custom events.
Code is super wacky but hm... it works?

Changes :
- Layer class now has a OnCustomEvent function
- Application class now has a OnCustomEvent method where it iterates all the layers and calls Layer::OnCustomEvent
- Added a new EventType as well as a new EventCategory
- CustomEvent class and CustomEventDispatcher class

How to use : 
I added a TestEvent example in Editor Layer, it works great. Right now it triggers the event on key press just for testing purposes, but it can works with any kind of condition as long as you call the CustomEvent properly.

2020-10-26 14:29 UTC, CleverSource commented
This is actually really awesome! Though I feel like having 2 different dispatchers is weird, maybe instead of splitting them, have a function (or struct variable) to set that will define a normal dispatcher as a custom one; which will in turn alter it's functionality a small bit?

Doing the above would remove lots of redundant code and make more sense in my opinion.

2020-10-26 14:35 UTC, Sausty commented
About the IsCustomEvent inheritance stuff, because GetEventType needs to be override and the type conflicts, it's impossible. It's also why i can't have a OnEvent function that groups hazel events and custom events.

2020-10-26 22:24 UTC, LovelySanta commented
I share the same opinions like CleverSource, 2 dispatchers is weird, it should share the same dispatcher

About the CustomEvent, that looks good, but I wonder what the difference is between CustomEvent and the ApplicationEvent class? Isn't that why the ApplicationEvent class is there? At least CustomEvent should be an ApplicationEvent since it's raised by the application, in that case it should be named as AppCustomEvent and be put in the ApplicationEvent.h file?

I feel like that would be the primary 'separation' and could be used by the dispatcher. After that, there should be another mechanism to seperate different derived classes of CustomEvent, what about the CustomEvent class providing a unique ID for each type of derived class? Maybe CustomEvent itself could then have the unique ID 0?

2020-10-27 02:26 UTC, CleverSource commented
I also believe doing what LovelySanta is stating would allow for a function such as `IsCustomEvent` which by default returns `false` but for `AppCustomEvent` will return `true` by overriding. This would allow you to remove `OnCustomEvent` from the Application class and just use `OnEvent` and alter one like of code for custom events.

I'll test this theory out later, but it sounds to me like it would work, if someone else can test this before I can please comment on your results!

2021-04-12 10:12 UTC, retrooper requested changes
EventCategoryNone should remain, "None" could be a constant for any enum.

2022-06-28 08:45 UTC, TheCherno commented
We'll be moving to C# soon for scripting, so a "gameplay" style event system isn't really needed in C++ (you would just build one of these in C#). The core engine event system is meant more for system/application events, such as the ones already present, and isn't meant to be extended.

2022-06-28 08:45 UTC, closed without merging