writing a readme file
TheCherno/Hazel pull request #51
Opened 2019-03-28 04:24 UTC by Khaledhn1

I was bored so I made this ReadMe file with the basic info about the Engine

2019-03-28 05:05 UTC, Khaledhn1 commented
@sagitarious12 alright I also added the links as you suggested

2019-04-08 00:12 UTC, saberslay commented
I think that this will make the read me file better to see all of the supported/not supported  platforms

##### ![](https://img.shields.io/badge/Windows-Supported-green.svg)
##### ![](https://img.shields.io/badge/Linux-Not%20Supported-red.svg)
##### ![](https://img.shields.io/badge/MacOS-Not%20Supported-red.svg)
##### ![](https://img.shields.io/badge/Android-Not%20Supported-red.svg)
##### ![](https://img.shields.io/badge/IOS-Not%20Supported-red.svg)

2019-04-12 22:40 UTC, Khaledhn1 commented
> 
> 
> I think that this will make the read me file better to see all of the supported/not supported platforms
> 
> ```
> ##### ![](https://img.shields.io/badge/Windows-Supported-green.svg)
> ##### ![](https://img.shields.io/badge/Linux-Not%20Supported-red.svg)
> ##### ![](https://img.shields.io/badge/MacOS-Not%20Supported-red.svg)
> ##### ![](https://img.shields.io/badge/Android-Not%20Supported-red.svg)
> ##### ![](https://img.shields.io/badge/IOS-Not%20Supported-red.svg)
> ```

good idea i implemented it and now the readme uses these images

2019-06-25 12:19 UTC, Gaztin commented
It's great to see this kind of enthusiasm, however I think it feels a little weird for collaborators to write the readme for the project. This part especially: https://github.com/TheCherno/Hazel/blob/f896aad1087a27149f988dd89babced06d34fc6c/README.md#L5

2019-06-25 12:20 UTC, Gaztin commented
That said, I do agree that the project needs a proper README

2019-09-06 12:13 UTC, Puddlestomper requested changes
Just some language things, and then the fact that Cherno's approval is required before this can be merged.

2019-09-06 12:13 UTC, Puddlestomper commented on README.md
> +The Hazel Engine is a 3D Application platform made by Yan "TheCherno" Chernikov an Australian YouTuber who creates programming tutorials around diffrent subjects from game development to general lang
```suggestion
The Hazel Engine is a 3D Application platform made by Yan "TheCherno" Chernikov, an Australian YouTuber who creates programming tutorials around different subjects from game development to general language tutorials.
```

2019-09-06 12:13 UTC, Puddlestomper commented on README.md
> +Consider Checking out [TheChernoProject ](https://www.youtube.com/user/TheChernoProject) Youtube Channel
```suggestion
Consider checking out [TheChernoProject](https://www.youtube.com/user/TheChernoProject) on YouTube.
```

2019-09-06 12:13 UTC, Puddlestomper commented on README.md
> +Also any support on [Patreon](https://www.patreon.com/thecherno) is always appreciated
This sentence requires approval from Cherno before being merged.
```suggestion
Also any support on [Patreon](https://www.patreon.com/thecherno) is always appreciated.
```

2019-09-06 12:13 UTC, Puddlestomper commented on README.md
> +Currently only Windows is supported with plans to support Linux,MacOS and maybe Android/ios in the future.
```suggestion
Currently only Windows is supported with plans to support Linux, MacOS and maybe Android or iOS in the future.
```

2019-09-06 12:13 UTC, Puddlestomper commented on README.md
> +##### 3. Open the project in visual studio
Maybe also add something about premake supporting other IDEs too?

```suggestion
##### 3. Open the project in Visual Studio
```

2019-09-06 17:26 UTC, LovelySanta commented
I'll say to not merge this, but instead use the readme from #82. If you want so, feel free to copy paste that one in a new PR that closes this one (and the issue related to this one).

2019-09-11 18:50 UTC, Puddlestomper commented
Seeing as Cherno made a readme file, this should either be closed or the features in this readme that are not in Cherno's one should be readded to this PR after merging in Cherno's one (which would mostly overwrite this readme I think?).

2019-09-12 06:39 UTC, LovelySanta commented
Yes, this can indeed be closed as cherno did write a readme. We will update the one in 82, but that is part of that PR and not this one.

Closing as this is resolved

2019-09-12 06:39 UTC, closed without merging

2024-06-08 19:58 UTC, hackerfinder64 commented
sabreslay is a hacker